#!/usr/bin/env bash

usage()
{
    cat << EOF
share [ -f | -r | -h ] [ -d TIME ] [ -l LEN ] FILENAME
  Easily scp a randomly titled, self-destructing version of your file.

  FILENAME : file to upload via ssh
  -d TIME : delete the file after TIME
  -r : upload file with random filename
  -f : upload file named by hashing file contents
  -n : upload file named by hashing file name
  -s : strip the extension from the filename, if any exists (default behavior is
   to preserve file extension, including when random or hash renaming is used)
  -l LEN : set length of random/hashed filename (default: 16)

  TIME is in the format 4d3h2m, in that order, any two parts can be omitted.
  With no suffix the unit of minutes is assumed.

EOF
}

USER=
DOMAIN=
DIR=

if [[ -z "$USER" || -z "$DOMAIN" || -z "$DIR" ]]; then
    echo "You must define the USER, DOMAIN and DIR variables (in the script)"
    exit
fi

# TODO: perhaps these two functions should fail without initial user
# intervention? This is where I picture the file-clobbering happening.

# echoes the upload-target filename
uploadto()
{
    filename=$1
    echo "~/'$DOMAIN/$DIR/$filename'"
    # single quotes escape spaces in filenames. if ~ is in the quotes it will
    # not be expanded.
}

# echoes the public link to the file
makelink()
{
    filename=$1
    echo "$DOMAIN/$DIR/$filename"
}

HASHLEN=16
RANDHASH=0
FILEHASH=0
NAMEHASH=0

while getopts "srnfl:d:" option; do
    case $option in
        r) RANDHASH=1 ;;
        f) FILEHASH=1 ;;
        n) NAMEHASH=1 ;;
        s) STRIPEXT=1 ;;
        l) HASHLEN=$OPTARG ;;
        d) DELETETIME=$OPTARG ;;
    esac
done

shift $(($OPTIND - 1))

if [ -z "$1" ]; then
    echo "ERROR - no file provided"
    usage
    exit
elif [ $((RANDHASH + FILEHASH + NAMEHASH)) -gt 1 ]; then
    echo "-r -f and -n flags are mutually exclusive"
    usage
    exit
fi

parsetime()
{
    dtime=0
    days=$(grep -Po "(^|[^0-9])\d+d" <<< $1 | tr -d "d")
    hours=$(grep -Po "(^|[^0-9])\d+h" <<< $1 | tr -d "dh")
    mins=$(grep -Po "(^|[^0-9])\d+m" <<< $1 | tr -d "hm")
    if [ ! -z "$days" ]; then dtime=$((days * 1440 + dtime)); fi
    if [ ! -z "$hours" ]; then dtime=$((hours * 60 + dtime)); fi
    if [ ! -z "$mins" ]; then dtime=$((mins + dtime)); fi
    echo $dtime
}

if [ ! -z "$DELETETIME" ]; then
    if [ ! -z $(grep -P "^(\d+d)?(\d+h)?(\d+m)?$" <<< "$DELETETIME") ];
    then
        offset=$(parsetime $DELETETIME)
    elif [ ! -z $(grep -P "^\d+$" <<< "$DELETETIME") ]; then
        offset=$DELETETIME
    else
        echo "invalid time string \"$DELETETIME\""
        exit
    fi
fi

source="$1"

if [[ $source =~ \. ]]; then  # has file extension
    # taken from http://stackoverflow.com/a/965072
    filename=$(basename "$source")
    extension=".${filename##*.}"
    filename=${filename%.*}
    if [ ! -z "$STRIPEXT" ]; then
        extension=""
    fi
else
    filename="$source"
    extension=""
fi

if [ $NAMEHASH -eq 1 ]; then
    hash=$(sha512sum <<< "$source" | cut -c1-$HASHLEN 2> /dev/null)
    remotebase="$hash$extension"
elif [ $RANDHASH -eq 1  ]; then
    # TODO: Is replacing / with - sufficient?
    hash=$(dd if=/dev/urandom count=1 2> /dev/null | base64 | tr -d "\n" | \
        cut -c1-$HASHLEN 2> /dev/null | tr -t "/" "-")
    remotebase="$hash$extension"
elif [ "$FILEHASH" -eq 1 ]; then
    hash=$(sha512sum "$source" | cut -c1-$HASHLEN 2> /dev/null)
    remotebase="$hash$extension"
else
    remotebase="$filename$extension"
fi

remotefile=$(uploadto "$remotebase")
link=$(makelink "$remotebase")

if scp "$source" "$USER@$DOMAIN:$remotefile"; then
    echo -n "$link"
    if which xclip > /dev/null; then
        xclip <<< "$link"
        echo -e "\t (link copied to clipboard)"
    fi

    remotecmd="at now + $offset minutes  2> /dev/null <<< \"rm $remotefile\""
    if [ ! -z "$offset" ]; then
        if ssh $USER@$DOMAIN 2> /dev/null <<< $remotecmd; then
            echo "Deletion scheduled. File will be deleted in $offset minutes."
        else
            echo "Failed to schedule deletion"
        fi
    fi
else
    echo "Failed uploading to $remotefile"
fi
